server:
  port: 8866

# BeanPostProcessorDemo
test:
  demo: zhangsan

# 接口幂等
spring:
  redis:
    cluster:
      nodes: 192.168.66.111:6379
    password: 123qwe
    database: 0
  datasource:
    # ?currentSchema=dss_decision&useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT+8&allowMultiQueries=true
    url: jdbc:postgresql://localhost:15431/dss?currentSchema=test
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver
    validation-query: SELECT 1