server:
  port: 8181

spring:
  application:
    name: dubbo-consumer
  cloud:
    nacos:
      discovery:
        #nacos注册中心地址
        server-addr: localhost:8848
        #nacos注册中心命名空间
        namespace: rfl
        #nacos注册中心分组
        group: dubbo

dubbo:
  registry:
    address: nacos://127.0.0.1:8848 #注册地址
    parameters:
      namespace: rfl
      group: dubbo
  application:
    name: dubbo-consumer #应用名
  consumer:
    timeout: 30000 #超时时间
